import {
  Loader2,
  Mail,
  CheckCircle,
  Lock,
  MailCheck,
  Home,
  Bell,
  Twitter,
  Hash,
  Bookmark,
  List,
  User,
  MoreHorizontal,
  Image,
  Smile,
  Calendar,
  MessageCircle,
  Repeat,
  Heart,
  Share,
  Search,
  LogOut,
  MapPin,
  Link,
  ChevronLeft,
  ChevronRight,
  UserCheck,
  UserPlus,
  Camera,
  Eye,
  EyeOff,
  Settings,
  Key,
  CalendarIcon,
  Globe,
  UserIcon,
  Pill,
  CalendarDays,
  LinkIcon,
  Users,
  Pencil,
  Moon,
  MoonIcon,
  Sun,
  ArrowRight,
  Briefcase,
  Bot,
  PenSquare,
  X
} from 'lucide-react'

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  checkCircle: CheckCircle,
  lock: Lock,
  mailCheck: MailCheck,
  home: Home,
  bell: Bell,
  twitter: Twitter,
  hash: Hash,
  bookmark: Bookmark,
  list: List,
  user: User,
  moreHorizontal: MoreHorizontal,
  image: Image,
  smile: Smile,
  calendar: Calendar,
  messageCircle: MessageCircle,
  repeat: Repeat,
  heart: Heart,
  share: Share,
  search: Search,
  logOut: LogOut,
  mapPin: MapPin,
  link: Link,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  userCheck: UserCheck,
  userPlus: UserPlus,
  camera: Camera,
  eye: Eye,
  eyeOff: EyeOff,
  settings: Settings,
  key: Key,
  calendarIcon: CalendarIcon,
  globe: Globe,
  userIcon: UserIcon,
  pill: Pill,
  calendarDays: CalendarDays,
  linkIcon: LinkIcon,
  users: Users,
  pencil: Pencil,
  moon: Moon,
  moonIcon: MoonIcon,
  sun: Sun,
  arrowRight: ArrowRight,
  briefcase: Briefcase,
  bot: Bot,
  penSquare: PenSquare,
  x: X
}
